### ISSUE TITLE
Replicate IMAP results on Replica

### ISSUE THREAD

**Issue by vincentcartillier** [tymoteuszb/implicit-slam#4]
I am currently trying to replicate the results from the paper on the Replica scenes . I am working with the room-0 in which I have recorded a random path of 2k frames using the [Habitat simulator](https://github.com/facebookresearch/habitat-sim). I have randomly selected locations in the scene and linked those locations using shortest path (see green path below). I have an agent step size of 1cm forward and 1.0deg rotations. And I render one RGB-D frame at each time step. 

I have a couple of questions:

(1) For the experiments using the Replica dataset, do you know how the random trajectories were generated? Was it by hand, if so, using which software? Or automatically (using which algorithm?)? On the figure 5 of the paper, I see a nice curvy random trajectory and I would like to replicate this data. The paper says it rendered 2000 frames from a randomly generated path. If you know about the path generation that would be great if you could you elaborate on this - like with details on the frame rate, agent step sizes (if any?), etc..

(2) What hyper parameters should be used for the Replica experiments? Currently I am using the following:

        uniform_samples_per_region = 4
        tracking_lr = 0.1
        tracking_iterations_per_frame = 10
        n_rays_per_tracking_iter = 240
        registration_threshold tp = 0.65
        photo-metric loss weight = 5
        window size = 5
        pixel samples = 200

I get the following result on an A40 GPU:

              #mapping iterations: 8,355
              #tracking iterations: 19,656
              depth residual: 0.12
              RGB residual: 0.06

![imap_topdown_output](https://user-images.githubusercontent.com/42780642/151401304-9ea89555-079c-4ef1-bcff-66535f49585c.png)

The tracking is just Ok. It seems far less accurate than what you have on Fig.5. In addition, the reconstruction seems very poor. Do you have any suggestions on how I could improve this result?

**Comment by tym-b** [comment]
Hi Vince,

Thanks for sharing your result. Please kindly note that this is not an official implementation of iMap, so it might perform worse than the original one. Unfortunately I haven't run my system on Replica dataset, so I can't really advise for hyperparameter tuning. In terms of results, I suspect rapid rotations, especially at the beginning of sequence, might be problematic. I'd suggest contacting the authors of iMap and asking how they generated their trajectories.

Also, with so powerful GPU you can try increasing window size, number of samples per region, and maybe number of tracking iterations. But I'd first try on a sequence with smoother motion.

**Comment by vincentcartillier** [comment]
Got it. Thanks for your answer! I will try that and I'll post results here if I can get anything better. 
Closing for now.
