### ISSUE TITLE
Virtual devices cannot be modified after being initialized

### ISSUE THREAD

**Issue by jamesgzl** [tymoteuszb/implicit-slam#5]
Hello, tymoteuszb,
Thanks for your great work of IMAP implement. However, I meet the problem when i running the code below

physical_devices = tf.config.list_physical_devices('GPU')
tf.config.set_logical_device_configuration(physical_devices[0],
    [tf.config.LogicalDeviceConfiguration(memory_limit=6144, experimental_priority=-1),
     tf.config.LogicalDeviceConfiguration(memory_limit=6144, experimental_priority=0)])
tf.config.list_logical_devices()

Report that 
Virtual devices cannot be modified after being initialized.

I wonder if you meet the same problem before. It's soooooo confusing!
Bset wish, James·GZL

**Comment by tym-b** [comment]
Hi James,

I believe you should run this cell only once in notebook's lifetime. Maybe you could add a simple check on the number of logical devices and only run this if it's needed, i.e. after restart. Hope that helps!

**Comment by jamesgzl** [comment]
Wow! I restart the cell and it does workkkk! Thanks for your reply.

**Comment by jamesgzl** [comment]
Hi, tymoteuszb, i'm james. and i'm sooooo SORRY for bothering you again,... 
when i run the cell of "Perform Simulaiton", after running for a while, i meet this problem.
![image](https://user-images.githubusercontent.com/86213011/156360593-816277b2-b804-432e-a11c-fffa6571f615.png)
It seems like tf.debug find somethin gose wrong...
And I plot the result for it.
![image](https://user-images.githubusercontent.com/86213011/156360709-1812d9fe-ebee-41b0-b952-28a45c72e55a.png)
All mess up/(ㄒoㄒ)/~~
I'm running the dataset of rgbd-tum-desk.
Did you meet the same problem before or where i can find the answer to solve it. I search the stackflow with find nothing😥😥😥😥
